# Generated by Django 4.2.3 on 2023-07-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(choices=[('BN', 'Bangladesh'), ('IN', 'India'), ('PK', 'Pakistan')], max_length=2)),
                ('city', models.CharField(choices=[('DH', 'Dhaka'), ('SY', 'Sylhet'), ('RJ', 'Rajshahi')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('FD', 'Food'), ('EN', 'Electronics'), ('CL', 'Cloth')], max_length=2)),
                ('address_1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(choices=[('DH', 'Dhaka'), ('SY', 'Sylhet'), ('RJ', 'Rajshahi')], max_length=2)),
                ('country', models.CharField(choices=[('BN', 'Bangladesh'), ('IN', 'India'), ('PK', 'Pakistan')], max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
